@startuml
:Agente: as agente
(Enviar solicitud cŕedido) as enviar
(Enviar solicitud cŕedido personal) as personal
(Enviar solicitud cŕedido\n empresarial) as empresarial

agente -> enviar
personal --|> enviar
empresarial --|> enviar

@enduml
